import { useCallback, useEffect, useMemo, useState } from 'react';
import { toast } from 'react-toastify';

import { Header } from '../../components/Header';
import { Result } from '../../components/Result';
import { Controls } from '../../components/Controls';
import { Execution } from '../../components/Execution';
import { Footer } from '../../components/Footer';

import { Customer } from '../../services/Customer';

import { Container, Main, LeftCenter, RightCenter } from './style';

import customersJson from './data.json';

type ExecutionProps = {
	date: Date;
	msg: string;
	type: 'info' | 'error' | 'function';
};

type CustomerData = {
	userid: string;
	name: string;
	email: string;
	order: string;
	sales: string;
};

type NotificationProps = {
	msg: string;
};

export const Home = () => {
	const [buttonClicked, setButtonClicked] = useState('');
	const [logs, setLogs] = useState<ExecutionProps[]>([]);
	const [notifications, setNotifications] = useState<NotificationProps[]>([]);
	const [data, setData] = useState<CustomerData[]>([]);
	const [done, setDone] = useState(false);

	const sendNotification = useCallback(({ msg }: NotificationProps) => {
		toast.info(msg, {
			position: 'bottom-right',
			autoClose: 1500,
			hideProgressBar: false,
			closeOnClick: true,
			pauseOnHover: false,
			draggable: false,
			progress: undefined,
			pauseOnFocusLoss: false,
			theme: 'dark',
		});

		const notification: NotificationProps = {
			msg,
		};
		setNotifications(notifications => [...notifications, notification]);
	}, []);

	const sendLog = useCallback(
		({ type, msg }: Omit<ExecutionProps, 'date'>) => {
			const log: ExecutionProps = {
				date: new Date(),
				msg,
				type,
			};
			setLogs(logs => [...logs, log]);

			if (type === 'function') {
				sendNotification({ msg });
			}
		},
		[sendNotification],
	);

	const customer = useMemo(
		() => new Customer('customer_db', sendLog),
		[sendLog],
	);

	const clearDB = useCallback(() => {
		sendLog({ type: 'function', msg: 'Clear DB Starts' });
		sendLog({
			type: 'info',
			msg: 'Delete all rows from the Customers database',
		});

		customer.removeAllRows();
	}, [sendLog, customer]);

	const loadDB = useCallback(() => {
		const customerData: CustomerData[] = [];

		sendLog({ type: 'function', msg: 'Load DB Starts' });
		sendLog({ type: 'info', msg: 'Load the Customers database' });

		customersJson.forEach(customer => {
			customerData.push(customer);
		});

		customer.initialLoad(customerData);
	}, [sendLog, customer]);

	const pushCustomer = useCallback((customer: CustomerData) => {
		setData(data => [...data, customer]);
	}, []);

	const queryDB = useCallback(() => {
		sendLog({ type: 'function', msg: 'Query DB Starts' });
		sendLog({ type: 'info', msg: 'Query the Customers in database' });

		customer.queryData(pushCustomer, setDone);
	}, [sendLog, customer, pushCustomer]);

	useEffect(() => {
		switch (buttonClicked) {
			case 'load':
				loadDB();
				setButtonClicked('');
				break;

			case 'clear':
				setData([]);
				clearDB();
				setButtonClicked('');
				break;
			case 'query':
				setData([]);
				queryDB();
				setButtonClicked('');
				break;
			default:
				setButtonClicked('');
		}
	}, [buttonClicked, loadDB, clearDB, queryDB]);

	useEffect(() => {
		toast.info('Data generated by mockaroo.com', {
			position: 'top-center',
			autoClose: 5000,
			hideProgressBar: false,
			closeOnClick: true,
			pauseOnHover: false,
			draggable: false,
			progress: undefined,
			pauseOnFocusLoss: false,
			theme: 'dark',
		});
	}, []);

	return (
		<>
			<Header notifications={notifications} />
			<Container>
				<Main>
					<LeftCenter>
						<Result done={done} data={data} />
						<Controls setButtonClicked={setButtonClicked} />
					</LeftCenter>
					<RightCenter>
						<Execution logs={logs} />
					</RightCenter>
				</Main>
				<Footer />
			</Container>
		</>
	);
};
